# Generated by Django 4.1.7 on 2023-03-03 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default="")),
                ('state', models.CharField(max_length=32, default="active")),
                ('expiration_date', models.DateField(null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('step_id', models.BigIntegerField(default=0)),
                ('categories_id', models.BigIntegerField(default=0)),
                ('files_id', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hedef',
                'verbose_name_plural': 'Hedefler',
                'ordering': ['created_at'],
            },
        ),
    ]
