# Generated by Django 4.1.7 on 2023-03-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('header', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=32)),
                ('expiration_date', models.DateField(null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('step_id', models.BigIntegerField(default=0)),
                ('categories_id', models.BigIntegerField(default=0)),
                ('files_id', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
